version: '3.7'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"
    links:
      - "postgres"
    env_file:
      - .env.defaults

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
